/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/checker/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create or refresh an anonymous checker session
         * @description Creates a new anonymous session if none exists, otherwise refreshes the current one. Always sets/refreshes the HttpOnly cookie "sid".
         */
        post: operations["createOrRefreshCheckerSession"];
        /**
         * Destroy current session (discard answers)
         * @description Invalidates the session server-side and clears the sid cookie.
         */
        delete: operations["deleteCheckerSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checker/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current checker state (answers + status + optional result) */
        get: operations["getCheckerState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/checker/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch answers (partial update, merge semantics)
         * @description Partial update. The backend merges provided keys into the persisted answers object. Keys not present in the request remain unchanged.
         */
        patch: operations["patchCheckerAnswers"];
        trace?: never;
    };
    "/api/checker/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate current answers and return result
         * @description Runs the rule engine on the currently persisted answers, stores the result, and returns the evaluated result (keys only).
         */
        post: operations["evaluateChecker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Sector: "retail" | "office" | "gastronomyHotel" | "accommodation" | "workshop" | "warehouse" | "cosmetics" | "dataCenter" | "selfService" | "other";
        /** @enum {string} */
        HospitalitySubtype: "beherbergung" | "iceSalon" | "otherGastro";
        /** @enum {string} */
        WorkshopSubtype: "tailor" | "shoeService" | "textilePickup" | "otherWorkshop";
        /** @enum {string} */
        OperatingPattern: "gfvoWindow" | "extendedHours" | "roundTheClock";
        /** @enum {string} */
        ClassificationKey: "noFacility" | "freistellungGFVO" | "needsPermit" | "individualAssessment";
        /** @enum {string} */
        ReasonKey: "externalVentilation" | "regulatedHazardousStorage" | "labelledHazardousStorage" | "musicExclusion" | "ippcSeveso" | "noFacilityDefinition" | "operatingHours" | "areaExceeded" | "accommodationBeds" | "accommodationBuildingUse" | "accommodationWellness" | "accommodationMeals" | "expectedImpairments" | "individualAssessment" | "freistellungSummary";
        /** @enum {string} */
        GfvoCategoryKey: "retail" | "office" | "warehouse" | "cosmetics" | "tailor" | "textilePickup" | "accommodation" | "iceSalon" | "dataCenter" | "infrastructureSite" | "embeddedFacility";
        /** @description Persisted answers for the checker. All fields are optional to support step-wise PATCHing. */
        CheckerAnswers: {
            sector?: components["schemas"]["Sector"];
            hospitalitySubtype?: components["schemas"]["HospitalitySubtype"];
            workshopSubtype?: components["schemas"]["WorkshopSubtype"];
            areaSqm?: number;
            personCount?: number;
            bedCount?: number;
            isStationary?: boolean;
            isOnlyTemporary?: boolean;
            buildingUseExclusive?: boolean;
            hasWellnessFacilities?: boolean;
            servesFullMeals?: boolean;
            zoningClarified?: boolean;
            buildingConsentPresent?: boolean;
            operatingPattern?: components["schemas"]["OperatingPattern"];
            hasExternalVentilation?: boolean;
            storesRegulatedHazardous?: boolean;
            storesLabelledHazardous?: boolean;
            usesLoudMusic?: boolean;
            ippcOrSevesoRelevant?: boolean;
            expectedImpairments?: boolean;
            locatedInInfrastructureSite?: boolean;
            locatedInApprovedComplex?: boolean;
            existingPermitHistory?: boolean;
        };
        CheckerAnswersPatch: {
            answers: components["schemas"]["CheckerAnswers"];
        };
        CheckerResult: {
            classification: components["schemas"]["ClassificationKey"];
            reasons: components["schemas"]["ReasonKey"][];
            /** @description Present when classification indicates GFVO matching (optional). */
            gfvoCategory?: components["schemas"]["GfvoCategoryKey"] | null;
        };
        CheckerState: {
            /** @description Server-side session identifier (not the cookie value) */
            sessionId: string;
            /** @enum {string} */
            status: "draft" | "finished";
            answers: components["schemas"]["CheckerAnswers"];
            /** @description Present after evaluation (optional). */
            result?: components["schemas"]["CheckerResult"] | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            expiresAt: string;
        };
        ProblemDetails: {
            /** @description A URI reference that identifies the problem type */
            type: string;
            /** @description Short, human-readable summary */
            title: string;
            /** @description HTTP status code */
            status: number;
            /** @description Human-readable explanation specific to this occurrence */
            detail?: string;
            /** @description A URI reference that identifies the specific occurrence */
            instance?: string;
            /** @description Optional application error code */
            code?: string;
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description Request validation failed */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
                "application/json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Missing or invalid session cookie */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
                "application/json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Session not found (expired or unknown) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
                "application/json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Unexpected server error */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
                "application/json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createOrRefreshCheckerSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session created/refreshed */
            200: {
                headers: {
                    /** @description HttpOnly session cookie (sid) */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckerState"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    deleteCheckerSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session deleted */
            204: {
                headers: {
                    /** @description Cleared cookie (sid=; Max-Age=0) */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["ServerError"];
        };
    };
    getCheckerState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current state for the session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckerState"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    patchCheckerAnswers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckerAnswersPatch"];
            };
        };
        responses: {
            /** @description Updated state after merge */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckerState"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
    evaluateChecker: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Evaluation result (keys only) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckerResult"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["ServerError"];
        };
    };
}
